# Generated by Django 4.2.4 on 2023-08-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome_usuario', models.CharField(max_length=30)),
                ('email_usuario', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
