# Generated by Django 4.2.4 on 2023-08-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='password',
        ),
    ]
