# Generated by Django 4.2.4 on 2023-08-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0004_alter_cadastro_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='confirmacao_senha',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='senha',
            field=models.CharField(max_length=128),
        ),
    ]
